sargol/sargol/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from web import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(urls)),
]


if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sargol/web/urls.py
from django.urls import path
from .views import home_page,ProductDetail,kham

app_name = 'web'

urlpatterns = [
    path('',home_page,name="home_page"),
    path('kham',kham, name='kham'),
    path('product/<slug:slug>',ProductDetail, name='ProductDetail')
]

sargol/productgallery/models.py
from django.db import models
from web.models import products
# Create your models here.
class gallery(models.Model):

    img = models.ImageField(upload_to='product_gallery')
    productt = models.ForeignKey(products, on_delete=models.CASCADE)

sargol/web/models.py
from django.db import models
from django.utils import timezone
from extensions.utils import jalali_converter
# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=100,verbose_name="عنوان دسته بندی")
    slug = models.SlugField(max_length=300,unique=True,verbose_name="آدرس دسته بندی")
    status = models.BooleanField(default=True,verbose_name="آیا نمایش داده شود")
    position = models.IntegerField(verbose_name="پوزیشن")
    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"
        ordering = ["position"]
    def __str__(self):
        return self.title
class products(models.Model):
    STATUS_CHOICEC =(('d','پیش ساز'),('p','منتشر شده'),)

    title = models.CharField(max_length=100,verbose_name="عنوان محصول")
    slug = models.SlugField(max_length=300,unique=True,verbose_name="آدرس محصول",default='', blank=True)
    category = models.ManyToManyField(Category,verbose_name="دسته بندی")
    price = models.CharField(max_length=200,verbose_name="قیمت")
    description = models.TextField(verbose_name="توضیحات")
    thumbnail = models.ImageField(upload_to="media",verbose_name="عکس")
    publish = models.DateTimeField(default=timezone.now,null=True,blank=True,verbose_name="زمان انتشار")
    created = models.DateTimeField(auto_now_add=True)
    upload = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1,choices=STATUS_CHOICEC,verbose_name="وضعیت")
    class Meta:
        verbose_name = "محصول"
        verbose_name_plural = "محصولات"
        ordering = ["-publish"]
    def __str__(self):
        return self.title
    def jpublish(self):
        return jalali_converter(self.publish)
    jpublish.short_description = "زمان انتشار"

class Articles(models.Model):
    STATUS_CHOICEC =(('d','پیش ساز'),('p','منتشر شده'),)

    title = models.CharField(verbose_name="عنوان مقاله",max_length=300)
    description = models.TextField(verbose_name="متن مقاله")
    category = models.ManyToManyField(Category,verbose_name="دسته بندی")
    status = models.CharField(max_length=1,choices=STATUS_CHOICEC,verbose_name="وضعیت")
    class Meta:
        verbose_name = "مقاله"
        verbose_name_plural = "مقالات"
    def __str__(self):
        return self.title

class Banners(models.Model):
    title = models.CharField(verbose_name="عنوان تغییر", max_length=50)
    category = models.ManyToManyField(Category,verbose_name="دسته بندی",blank=True)
    banner1=models.FileField(verbose_name="بنر یک", upload_to="products/banners/",
        max_length=100,null=True,blank=True)
    banner2=models.FileField(verbose_name="بنر دو", upload_to="products/banners/",
        max_length=100,null=True,blank=True)
    banner3=models.FileField(verbose_name="بنر سه", upload_to="products/banners/",
        max_length=100,null=True,blank=True)

    class Meta:
        verbose_name = "بنر"
        verbose_name_plural = "بنر ها"
    def __str__(self):
        return self.title

sargol/productgallery/views.py
from django.shortcuts import render

# Create your views here.

sargol/web/views.py
from django.shortcuts import render, get_list_or_404
from .models import products,Articles,Category,Banners
from productgallery.models import gallery

# Create your views here.
def home_page(request):
    context = {
        "products":products.objects.filter(status='p'),
        "articles":Articles.objects.filter(status='p'),
        "categoryes":Category.objects.filter(status=True),
        "banners":Banners.objects.get()

    }
    return render(request,"index.html",context)

def ProductDetail(request,slug):
    context = {
        "product":products.objects.get(slug=slug),
        "products":products.objects.filter(status='p')[:4],
        "categoryes":Category.objects.filter(status=True),
        "banners":Banners.objects.get(),
        "images":gallery.objects.all()
    }
    return render(request,"ProductDetail.html",context)

def kham(request):
    context={
        "banners":Banners.objects.get()
    }
    return render(request,"mahsulate-kham.html",context)

sargol/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
  <head><!--moein parvizi(+989107215381)-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      چاپ محصولات هنری علی
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/uniq-card-style.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.elevateZoom-3.0.8.min.js' %}"></script>
    </head>
  <body><!--moein parvizi(+989107215381)-->

    <!--alert azmayeshi-->
    <div class="alert alert-success alert-dismissible fade show text-center">
      <button class="close" data-dismiss="alert">&times;</button>
      <strong>نسخه آزمایشی</strong>
    </div>

    <!--scroll to the top button-->
    <button onclick="topFunction()" id="scrolltotopbtn" title="Go to top"><i class="fa fa-arrow-up"></i></button>

    <!--social engection
    <a href="#">
      <div class="fa fa-telegram fixed-bottom"></div>
    </a>
    <a href="#">
      <div class="fa fa-instagram fixed-bottom"></div>
    </a>-->

<!--top page-->
    <header class="animateMdown05s">
      <div class="row container-fluid" style="margin:0;">

      <div class="col-lg-9 d-none d-sm-block">
        <!--slider-->
        <div id="demo" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ul class="carousel-indicators">
            <li data-target="#demo" data-slide-to="0" class="active"></li>
            <li data-target="#demo" data-slide-to="1"></li>
            <li data-target="#demo" data-slide-to="2"></li>
          </ul>
          <!-- The slideshow -->
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="{{banners.banner1.url}}" alt="banner" width="1100" height="500">
            </div>
            <div class="carousel-item">
              <img src="{{banners.banner2.url}}" alt="banner" width="1100" height="500">
            </div>
            <div class="carousel-item">
              <img src="{{banners.banner3.url}}" alt="banner" width="1100" height="500">
            </div>
          </div>
          <!-- Left and right controls -->
          <a class="carousel-control-prev" href="#demo" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
          </a>
          <a class="carousel-control-next" href="#demo" data-slide="next">
            <span class="carousel-control-next-icon"></span>
          </a>
        </div>
      </div>

        <div class="col-lg-3 d-none d-lg-block">
          <img src="{% static 'img/logo.jpg' %}" alt="logo" style="width: 100%;">
        </div>
      </div>

    </header>


    <!--navbar-->
    <nav class="navbar navbar-expand-sm nav-bg sticky-top justify-content-center animateMdown1s">
        <button onclick="show()" class="navbar-toggler" data-toggle="collapse" data-target="#collapse_target">
          <i class="fa fa-bars"></i>
        </button>
        <a class="navbar-brand" href="#">
          <img src="{% static 'img/logo.jpg' %}" style="width:70px;" alt="چاپ هنری علی">
        </a>
        <div class="collaps navbar-collapse" id="collapse_target">
          <ul class="navbar-nav">
            <li class="nav-item khane">
              <a class="nav-link" href="{% url 'web:home_page' %}"> خانه <i class="fa fa-home"></i></a>
            </li>
            <li class="nav-item kham">
              <a class="nav-link" href="{% url 'web:kham' %}">محصولات خام</a>
            </li>
            <li class="nav-item dropdown menu-aria">
              <a class="nav-link dropdwon-toggle" href="#" id="mega-one" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                خدمات چاپی
                <i class="fa fa-angle-down"></i>
              </a>
              <div class="dropdown-menu mega-aria scrollmenu" style="paddig:20px;" aria-labelledby="mega-one">

                <div class="row">
                  <div class="col-12  col-sm-6 col-lg-4 col-xl-3" style="padding:10px">
                    <h6 class="h5-nav-dropdown" style="color:#8b2c70">چاپ سابلیمیشن</h6>
                    <a href="product/muge" class="dropdown-item menu-contact">(لیوان)ماگ</a>
                    <a href="product/mask" class="dropdown-item menu-contact">ماسک</a>
                    <a href="product/tshert" class="dropdown-item menu-contact">تیشرت</a>
                    <a href="product/sueishert" class="dropdown-item menu-contact">سوییشرت</a>
                    <a href="product/cap" class="dropdown-item menu-contact">کلاه</a>
                    <a href="product/parcham" class="dropdown-item menu-contact">پرچم</a>
                    <a href="product/boshghab" class="dropdown-item menu-contact">بشقاب</a>
                    <a href="product/puzzle" class="dropdown-item menu-contact">پازل</a>
                    <a href="product/mouse-pad" class="dropdown-item menu-contact">پد ماوس</a>
                    <a href="product/shall-rusari" class="dropdown-item menu-contact">شال و روسری</a>
                    <a href="product/kusan" class="dropdown-item menu-contact">کوسن</a>
                    <a href="product/saat" class="dropdown-item menu-contact">ساعت</a>
                    <a href="product/ghaliche" class="dropdown-item menu-contact">قالیچه</a>
                  </div>
                  <div class="col-12 col-sm-6 col-lg-4 col-xl-3" style="padding:10px">
                  <h6 class="h5-nav-dropdown" style="color:#8b2c70">چاپ افست</h6>
                    <a href="product/card-visit" class="dropdown-item menu-contact">کارت ویزیت</a>
                    <a href="product/factor" class="dropdown-item menu-contact">فاکتور</a>
                    <a href="product/tracket" class="dropdown-item menu-contact">تراکت</a>
                    <a href="product/sarbarg" class="dropdown-item menu-contact">سربرگ</a>
                    <a href="product/label" class="dropdown-item menu-contact">لیبل</a>
                    <a href="product/packet" class="dropdown-item menu-contact">پاکت</a>
                  </div>
                  <div class="col-12 col-sm-6 col-lg-4 col-xl-3" style="padding:10px">
                  <h6 class="h5-nav-dropdown" style="color:#8b2c70">چاپ دیجی تال</h6>
                    <a href="product/aks-shasti" class="dropdown-item menu-contact">عکس و شاستی</a>
                    <a href="product/sarresid" class="dropdown-item menu-contact">سر رسید</a>
                    <a href="product/banner" class="dropdown-item menu-contact">بنز</a>
                    <a href="product/taghvim-divari" class="dropdown-item menu-contact">تقویم دیواری</a>
                    <a href="product/taghvim-rumizi" class="dropdown-item menu-contact">تقویم رو میزی</a>
                    <a href="product/estand" class="dropdown-item menu-contact">استند</a>
                  </div>
                  <div class="col-12 col-sm-6 col-lg-4 col-xl-3" style="padding:10px">
                  <h6 class="h5-nav-dropdown" style="color:#8b2c70">سایر خدمات</h6>
                    <a href="product/disk" class="dropdown-item menu-contact">چاپ روی دیسک</a>
                    <a href="product/barchasb-hararati" class="dropdown-item menu-contact">برچسب حرارتی</a>
                    <a href="product/shabrang-sticker" class="dropdown-item menu-contact">شب رنگ واستیکر</a>
                    <a href="product/ghabe-aks" class="dropdown-item menu-contact">قاب عکس</a>
                    <a href="product/berezent-charm" class="dropdown-item menu-contact">برزنت و چرم</a>
                    <a href="product/addie-ghoran-amvat" class="dropdown-item menu-contact">ادعیه قرآن واموات</a>
                    <a href="product/tarahi-site" class="dropdown-item menu-contact">طراحی سایت</a>
                  </div>
                </div>

              </div>
            </li>



          </ul>
        </div>
    </nav>

{% block main %}



{% endblock %}

<!--footer-->
    <footer class="animateMdown2-5s">
      <div class="container-fluid sec-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="card desc-box">
                        <div class="card-body">
                            <div class="card-title">زمان پاسخ گویی</div>
                            <div class="card-text">
                              از ساعت 9:00 صبح تا ساعت 18:00 عصر پاسخگوی مشتریان هستیم به جز روز های تعطیل و پاسخگویی در واتس اپ 24 ساعته
                            </div>
                        </div>
                    </div><!--.card-->
                </div><!--.col-->
                <div class="col">
                    <div class="card desc-box">
                        <div class="card-body">
                            <div class="card-title">ارتباط با ما</div>
                            <div class="card-text">
                                <div class="row">
                                    <div class="col">
                                        <i class="fa fa-phone ml-3"></i>
                                        09193174571-02155250612
                                    </div><!--.col-->
                                </div><!--.row-->
                                <div class="row">
                                    <div class="col">
                                        <i class="fa fa-whatsapp ml-3"></i>
                                        09194772447
                                    </div><!--.col-->
                                </div><!--.row-->
                                <div class="row">
                                    <div class="col">
                                        <i class="fa fa-map-marker ml-3"></i>
                                        <span>به دلایل بیماری کرونا به صورت غیر حضوری پذیرفته می شود</span>
                                    </div><!--.col-->
                                </div><!--.row-->
                                <div class="row">
                                    <div class="col">
                                        <i class="fa fa-envelope-open ml-3"></i>
                                        <span>mhossein20@yahoo.com</span>
                                    </div><!--.col-->
                                </div><!--.row-->
                            </div><!--.card-text-->
                        </div>
                    </div><!--.card-->
                </div><!--.col-->
                <div class="col text-center">
                    <img src="{% static 'img/logo.png' %}" alt="خدمات چاپی علی" style="width:200px;" class="mb-3">
                    <br class="clearfix">
                    <a href="https://www.instagram.com/chape.tehran/" class="snip1472"><i class="fa fa-instagram"></i></a>
                    <a href="https://t.me/chapeshatare" class="snip1472"><i class="fa fa-telegram"></i></a>
                </div><!--.col-->
            </div><!--.row-->
        </div>
      </div>
      <div class="container-fluid sec-sub-footer">
        <div class="container">
            <div class="row">
                <div class="col-12 col-sm-6">
                    <span>تمامی حقوق سایت متعلق به خدمات چاپی سارگل می باشد.</span>
                </div><!--.col-->
                <div class="col-12 col-sm-6 text-left">
                    <a href="#" class="f-light text-dark">طراحی و توسعه:</a>
                    <a href="#"  class="f-light text-dark">معین پرویزی ۰۹۱۰۷۲۱۵۳۸۱</a>
                </div><!--.col-->
            </div><!--.row-->
        </div>
      </div>
    </footer>
    <!--moein parvizi(+989107215381)-->
    <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>

  </body>
</html>

sargol/templates/baseNoHeader.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
  <head><!--moein parvizi(+989107215381)-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      چاپ محصولات هنری علی
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/uniq-card-style.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.elevateZoom-3.0.8.min.js' %}"></script>
    </head>
  <body><!--moein parvizi(+989107215381)-->

    <!--alert azmayeshi-->
    <div class="alert alert-success alert-dismissible fade show text-center">
      <button class="close" data-dismiss="alert">&times;</button>
      <strong>نسخه آزمایشی</strong>
    </div>

    <!--scroll to the top button-->
    <button onclick="topFunction()" id="scrolltotopbtn" title="Go to top"><i class="fa fa-arrow-up"></i></button>

    <!--social engection
    <a href="#">
      <div class="fa fa-telegram fixed-bottom"></div>
    </a>
    <a href="#">
      <div class="fa fa-instagram fixed-bottom"></div>
    </a>-->

<!--top page-->
    <header class="animateMdown05s">
      <div class="row container-fluid" style="margin:0;">


    </header>


    <!--navbar-->
    <nav class="navbar navbar-expand-sm nav-bg sticky-top justify-content-center animateMdown1s">
        <button onclick="show()" class="navbar-toggler" data-toggle="collapse" data-target="#collapse_target">
          <i class="fa fa-bars"></i>
        </button>
        <a class="navbar-brand" href="#">
          <img src="{% static 'img/logo.jpg' %}" style="width:70px;" alt="چاپ هنری علی">
        </a>
        <div class="collaps navbar-collapse" id="collapse_target">
          <ul class="navbar-nav">
            <li class="nav-item khane">
              <a class="nav-link" href="{% url 'web:home_page' %}"> خانه <i class="fa fa-home"></i></a>
            </li>
            <li class="nav-item kham">
              <a class="nav-link" href="{% url 'web:kham' %}">محصولات خام</a>
            </li>
            <li class="nav-item dropdown menu-aria">
              <a class="nav-link dropdwon-toggle" href="#" id="mega-one" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                خدمات چاپی
                <i class="fa fa-angle-down"></i>
              </a>
              <div class="dropdown-menu mega-aria scrollmenu" style="paddig:20px;" aria-labelledby="mega-one">
                <div class="row">

                  <div class="col-12  col-sm-6 col-lg-4 col-xl-3" style="padding:10px">
                    <h6 class="h5-nav-dropdown" style="color:#8b2c70">چاپ سابلیمیشن</h6>
                    <a href="product/muge" class="dropdown-item menu-contact">(لیوان)ماگ</a>
                    <a href="product/mask" class="dropdown-item menu-contact">ماسک</a>
                    <a href="product/tshert" class="dropdown-item menu-contact">تیشرت</a>
                    <a href="product/sueishert" class="dropdown-item menu-contact">سوییشرت</a>
                    <a href="product/cap" class="dropdown-item menu-contact">کلاه</a>
                    <a href="product/parcham" class="dropdown-item menu-contact">پرچم</a>
                    <a href="product/boshghab" class="dropdown-item menu-contact">بشقاب</a>
                    <a href="product/puzzle" class="dropdown-item menu-contact">پازل</a>
                    <a href="product/mouse-pad" class="dropdown-item menu-contact">پد ماوس</a>
                    <a href="product/shall-rusari" class="dropdown-item menu-contact">شال و روسری</a>
                    <a href="product/kusan" class="dropdown-item menu-contact">کوسن</a>
                    <a href="product/saat" class="dropdown-item menu-contact">ساعت</a>
                    <a href="product/ghaliche" class="dropdown-item menu-contact">قالیچه</a>
                  </div>
                  <div class="col-12 col-sm-6 col-lg-4 col-xl-3" style="padding:10px">
                  <h6 class="h5-nav-dropdown" style="color:#8b2c70">چاپ افست</h6>
                    <a href="product/card-visit" class="dropdown-item menu-contact">کارت ویزیت</a>
                    <a href="product/factor" class="dropdown-item menu-contact">فاکتور</a>
                    <a href="product/tracket" class="dropdown-item menu-contact">تراکت</a>
                    <a href="product/sarbarg" class="dropdown-item menu-contact">سربرگ</a>
                    <a href="product/label" class="dropdown-item menu-contact">لیبل</a>
                    <a href="product/packet" class="dropdown-item menu-contact">پاکت</a>
                  </div>
                  <div class="col-12 col-sm-6 col-lg-4 col-xl-3" style="padding:10px">
                  <h6 class="h5-nav-dropdown" style="color:#8b2c70">چاپ دیجی تال</h6>
                    <a href="product/aks-shasti" class="dropdown-item menu-contact">عکس و شاستی</a>
                    <a href="product/sarresid" class="dropdown-item menu-contact">سر رسید</a>
                    <a href="product/banner" class="dropdown-item menu-contact">بنز</a>
                    <a href="product/taghvim-divari" class="dropdown-item menu-contact">تقویم دیواری</a>
                    <a href="product/taghvim-rumizi" class="dropdown-item menu-contact">تقویم رو میزی</a>
                    <a href="product/estand" class="dropdown-item menu-contact">استند</a>
                  </div>
                  <div class="col-12 col-sm-6 col-lg-4 col-xl-3" style="padding:10px">
                  <h6 class="h5-nav-dropdown" style="color:#8b2c70">سایر خدمات</h6>
                    <a href="product/disk" class="dropdown-item menu-contact">چاپ روی دیسک</a>
                    <a href="product/barchasb-hararati" class="dropdown-item menu-contact">برچسب حرارتی</a>
                    <a href="product/shabrang-sticker" class="dropdown-item menu-contact">شب رنگ واستیکر</a>
                    <a href="product/ghabe-aks" class="dropdown-item menu-contact">قاب عکس</a>
                    <a href="product/berezent-charm" class="dropdown-item menu-contact">برزنت و چرم</a>
                    <a href="product/addie-ghoran-amvat" class="dropdown-item menu-contact">ادعیه قرآن واموات</a>
                    <a href="product/tarahi-site" class="dropdown-item menu-contact">طراحی سایت</a>
                  </div>
                </div>
              </div>
            </li>

          </ul>
        </div>
    </nav>

{% block main %}



{% endblock %}

<!--footer-->
    <footer class="animateMdown2-5s">
      <div class="container-fluid sec-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="card desc-box">
                        <div class="card-body">
                            <div class="card-title">زمان پاسخ گویی</div>
                            <div class="card-text">
                              از ساعت 9:00 صبح تا ساعت 18:00 عصر پاسخگوی مشتریان هستیم به جز روز های تعطیل و پاسخگویی در واتس اپ 24 ساعته
                            </div>
                        </div>
                    </div><!--.card-->
                </div><!--.col-->
                <div class="col">
                    <div class="card desc-box">
                        <div class="card-body">
                            <div class="card-title">ارتباط با ما</div>
                            <div class="card-text">
                                <div class="row">
                                    <div class="col">
                                        <i class="fa fa-phone ml-3"></i>
                                        09193174571-02155250612
                                    </div><!--.col-->
                                </div><!--.row-->
                                <div class="row">
                                    <div class="col">
                                        <i class="fa fa-whatsapp ml-3"></i>
                                        09194772447
                                    </div><!--.col-->
                                </div><!--.row-->
                                <div class="row">
                                    <div class="col">
                                        <i class="fa fa-map-marker ml-3"></i>
                                        <span>به دلایل بیماری کرونا به صورت غیر حضوری پذیرفته می شود</span>
                                    </div><!--.col-->
                                </div><!--.row-->
                                <div class="row">
                                    <div class="col">
                                        <i class="fa fa-envelope-open ml-3"></i>
                                        <span>mhossein20@yahoo.com</span>
                                    </div><!--.col-->
                                </div><!--.row-->
                            </div><!--.card-text-->
                        </div>
                    </div><!--.card-->
                </div><!--.col-->
                <div class="col text-center">
                    <img src="{% static 'img/logo.png' %}" alt="خدمات چاپی علی" style="width:200px;" class="mb-3">
                    <br class="clearfix">
                    <a href="https://www.instagram.com/chape.tehran/" class="snip1472"><i class="fa fa-instagram"></i></a>
                    <a href="https://t.me/chapeshatare" class="snip1472"><i class="fa fa-telegram"></i></a>
                </div><!--.col-->
            </div><!--.row-->
        </div>
      </div>
      <div class="container-fluid sec-sub-footer">
        <div class="container">
            <div class="row">
                <div class="col-12 col-sm-6">
                    <span>تمامی حقوق سایت متعلق به خدمات چاپی سارگل می باشد.</span>
                </div><!--.col-->
                <div class="col-12 col-sm-6 text-left">
                    <a href="#" class="f-light text-dark">طراحی و توسعه:</a>
                    <a href="#"  class="f-light text-dark">معین پرویزی ۰۹۱۰۷۲۱۵۳۸۱</a>
                </div><!--.col-->
            </div><!--.row-->
        </div>
      </div>
    </footer>
    <!--moein parvizi(+989107215381)-->
    <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>

  </body>
</html>

sargol/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
  <!--cards-->
  <section class="page-effect animateMdown1-5s" id="cards">
    <div class="container-fluid" style="padding:0px;">
      <div class="md-5">

        <div class="head-page">
          <h1 class="text-center py-5">محصولات ما</h1>
          <hr style="line-height:1px;width:100%;background-color:#fff;">

          <div class="row row-cards container-fluid">

            {% for product in products %}
            <div class="col-xl-2 col-lg-3 col-md-6 col-sm-6 col-12">
              <div class="card">
                <img src="{{product.thumbnail.url}}" alt="{{product.title}}" class="parcham-img card-img-top">
                <div class="card-body">
                  <h5 class="head-card h5-card text-center">{{product.title}}</h5>
                  <hr class="hr-card">
                  <a href="{% url 'web:ProductDetail' product.slug %}" class="btn stretched-link etelaate-bishtar">اطلاعات بیشتر</a>
                </div>
              </div>
            </div>
            {% endfor %}

          </div>
        </div>
      </div>
    </div>
  </section>


  <article class="animateMdown1s">
<!--accordion-->
    <div class="middle-page">
      <div class="head-page" style="background-color: #aad576;">
        <h2 class="text-center py-5">اعلانیه های جدید</h2>
        <hr style="line-height:1px;width:100%;background-color:#fff;">
        <div class="row container-fluid">

          <div class="col-lg-6 col-md-12">
            <div id="accordion">

              {% for article in articles %}
              <div class="card card-link">
                <div class="dropdown-accordion card-header" data-toggle="collapse" href="#collapseOne">
                  {{article.title}}
                </div>
                <div id="collapseOne" class="collapse show" data-parent="#accordion">
                  <div class="card-body text-accordion">
                    {{article.description}}
                  </div>
                </div>
              </div>
              {% endfor %}

            </div>
          </div>

        </div>
      </div>
    </div>
  </article>
{% endblock main %}

sargol/templates/mahsulate-kham.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    <section class="page-effect bezoodi-bg animateMdown1-5s" id="cards">
      <h1 contenteditable spellcheck="false" class="h1-kham">به زودی</h1>
    </section>
{% endblock main %}